// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBZnEthGKEDodEUXaV1McFgHRjAgCRv4',
    appId: '1:1096246930842:web:6348c54aa35027cf451e23',
    messagingSenderId: '1096246930842',
    projectId: 'qrscanatten',
    authDomain: 'qrscanatten.firebaseapp.com',
    storageBucket: 'qrscanatten.firebasestorage.app',
    measurementId: 'G-T6ZH75RKZV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJsC7iARj1Yvmtc5JKZDgftFtK8zppX1Q',
    appId: '1:1096246930842:ios:a2a9101f7f605282451e23',
    messagingSenderId: '1096246930842',
    projectId: 'qrscanatten',
    storageBucket: 'qrscanatten.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJsC7iARj1Yvmtc5JKZDgftFtK8zppX1Q',
    appId: '1:1096246930842:ios:a2a9101f7f605282451e23',
    messagingSenderId: '1096246930842',
    projectId: 'qrscanatten',
    storageBucket: 'qrscanatten.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBZnEthGKEDodEUXaV1McFgHRjAgCRv4',
    appId: '1:1096246930842:web:3a9ab5a6ccfaa8cf451e23',
    messagingSenderId: '1096246930842',
    projectId: 'qrscanatten',
    authDomain: 'qrscanatten.firebaseapp.com',
    storageBucket: 'qrscanatten.firebasestorage.app',
    measurementId: 'G-829G3ZXT83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgjpQmDlu98Sm10QfMVLC7LoOaFldzx4',
    appId: '1:1096246930842:android:baaf959900fe21ab451e23',
    messagingSenderId: '1096246930842',
    projectId: 'qrscanatten',
    storageBucket: 'qrscanatten.firebasestorage.app',
  );

}